# Site settings
title: Eleanor Kiefel Haggerty
email: eleanorakh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Eleanor is currently traipsing around Europe armed with a love of the unknown and a desire for delicious food.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eleanorakh.github.io" # the base hostname & protocol for your site
twitter_username: eleanorkh
github_username: eleanorakh

# Build settings
markdown: kramdown
