# # Site settings
# title: Eleanor Kiefel Haggerty
# email: eleanorakh@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
#   Eleanor is currently traipsing around Europe armed with a love of the unknown and a desire for delicious food.
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://eleanorakh.github.io" # the base hostname & protocol for your site
# twitter_username: eleanorkh
# github_username: eleanorakh

# Build settings
markdown: kramdown

# Jekyll configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Eleanor'
description: "Exploring the world"

# Author's info
author: 'Eleanor Kiefel Haggerty'
# edit 'categories' in the front matter of every post to match this username
nickname: eleanor
bio: 'After fourteen months of travel to 28 countries, Eleanor returned to Australia, moved to Melbourne and embarked on journey to learn to program.'
location: 'Melbourne, Australia'
url: 'http://eleanorkh.com'
image: 'assets/images/casper.png'

short_url: 'eleanorkh.com'
# google_analytics: UA-69281367-1
# disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /eleanorkh/

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: eleanoarkh
repo: eleanorakh.github.io
branch: master
relative_source: ../eleanorkh/
# destination: ../jasper-pages/
production_url:  https://eleanorakh.github.io
source_url:      https://github.com/eleanorakh/eleanorakh.github.io/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
